### ISSUE TITLE
Compilation fails with undefined function erlang:get_stacktrace/0

### ISSUE THREAD

**Issue by sezaru** [elixir-lang/elixir#11047]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.0 (compiled with Erlang/OTP 24)

* Operating system: 
Ubuntu 20.04

### Current behavior

Compiling a code that depends on `sleeplocks` which in case depends on `rebar3_hex` fails with the following error with new OTP 24:

```bash
===> Fetching rebar3_hex v6.11.4
===> Version cached at /home/sezdocs/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.11.4.tar is up to date, reusing it
escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/rebar3/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
** (Mix) Could not compile dependency :sleeplocks, "/home/sezdocs/.mix/rebar3 bare compile --paths /home/sezdocs/project/endpoints/_build/dev/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile sleeplocks", update it with "mix deps.update sleeplocks" or clean it with "mix deps.clean sleeplocks"
```
I tried this with both Elixir 1.12.1 and 1.12.0, and also OTP 24.0.1 and 24.0.2.

**Comment by josevalim** [comment]
Please run `mix local.rebar` to update your Rebar installation. Or if you have Rebar3 locally installed (which rebar3 will tell you the location), then update it too. This issue is cause by an incompatible Rebar version with Erlang OTP 24.

**Comment by sezaru** [comment]
Unfortunately, that didn't work, I think I already have the latest version (6.11.4).

This is the output of the command anyway:
```bash
$ mix local.rebar
/home/sezdocs/.mix/rebar already exists, overwrite? [Yn] Y
* creating /home/sezdocs/.mix/rebar

/home/sezdocs/.mix/rebar3 already exists, overwrite? [Yn] Y
* creating /home/sezdocs/.mix/rebar3
```

**Comment by sezaru** [comment]
I don't know why, but changing my HEX_MIRROR fixed it.

What I did was the following:
```bash
HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.hex
HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.rebar
```

**Comment by josevalim** [comment]
“ 6.11.4” is not a valid Rebar version but glad it was addressed. This is not an Elixir issue after all, just outdated Rebar.

**Comment by juanperi** [comment]
the same happens inside docker, using the image `hexpm/elixir:1.12.1-erlang-24.0.2-alpine-3.13.3`
```
docker run -it hexpm/elixir:1.12.1-erlang-24.0.2-alpine-3.13.3 sh
```
It installs version 3.13.3 by default 
```
/ # mix local.rebar
/ # ~/.mix/rebar3 --version
rebar 3.13.3 on Erlang/OTP 24 Erts 12.0.2
```
But using the jsdelvr cdn, it installs 3.15.1
```
/ # HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.rebar
/ # ~/.mix/rebar3 --version
rebar 3.15.1 on Erlang/OTP 24 Erts 12.0.2
```

At this point i'm not even sure where I can report this, or where the issue is. Any pointer?

**Comment by josevalim** [comment]
Ok, I can reproduce it. It seems Hex is returning the wrong Rebar but the mirror is using a cache with the correct answer. This is a regression on the server, we are investigating. Thanks!

**Comment by josevalim** [comment]
Fixed, thanks!

**Comment by fr4nz909** [comment]
What a community! 🚀🚀🚀

**Comment by rinpatch** [comment]
Doesn't appear fixed for me.

My Elixir version is:
```
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```

I tried running `mix local.rebar`, removing `~/.mix/` and `~/.cache/rebar3` and installing rebar again, removing project build and deps files, using the jsdelivr cdn, but I still get this error:
```
===> Fetching rebar3_hex v6.11.4
===> Downloaded package, caching at /home/rin/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.11.4.tar
escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/rebar3/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
** (Mix) Could not compile dependency :sleeplocks, "/home/rin/.mix/rebar3 bare compile --paths="/home/rin/sw/cachex/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile sleeplocks", update it with "mix deps.update sleeplocks" or clean it with "mix deps.clean sleeplocks"
````

What am I doing wrong?

**Comment by josevalim** [comment]
@rinpatch just to be sure, what does `which rebar3` return? Also, what does `~/.mix/rebar3 --version` return? Finally, if you are using `asdf`, remember you need to rehash the paths or similar after you install rebar3.

**Comment by jb0gie** [comment]
hi hi i'm having the same issue as @rinpatch 
ss1: using `mix local.rebar`
ss2: using `HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.rebar`
![image](https://user-images.githubusercontent.com/6885227/127049521-71dcd8e2-ccac-4cf1-a82a-a4b0505b16ae.png)
![image](https://user-images.githubusercontent.com/6885227/127049772-227ad652-307b-422d-896c-f5f002d7821e.png)

**Comment by josevalim** [comment]
@jb0gie sorry to hear about that. Please try upgrading your Elixir version and running `mix local.rebar`. Or running on Erlang/OTP 23 instead.
