### ISSUE TITLE
Always emitting column and line number in errors

### ISSUE THREAD

**Issue by viniciusmuller** [elixir-lang/elixir#12591]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:32:16] [ds:32:16:10] [async-threads:1] [jit:ns]

Elixir 1.15.0-rc.0 (a1e0726) (compiled with Erlang/OTP 25)
```

### Operating system

```
Linux nixos 6.1.24 #1-NixOS SMP PREEMPT_DYNAMIC Thu Apr 13 14:55:40 UTC 2023 x86_64 GNU/Linux
```

### Current behavior

Currently, it seems that many times Code.diagnostic only returns the position that an error happened in a file, leaving making it hard to work with it later and a bit confusing:

Given a file `test.exs` file:
```ex
defmodule Foo do 

  def ~R(_) do 
    10
  end

  def bar do 
    atom =  :hello!
    list = [1, 2, 3]

    if atom do 
      Enum.map(list, &fake_fun/1)
    end
  end
end


Foo.bar()
```

This is the current output:
```
$ make && ./bin/elixir test.exs
error: undefined function fake_fun/1 (expected Foo to define such a function or for it to be imported, but none are available)
  test.exs:12: Foo.bar/0
```

### Expected behavior

`position` should also contain the column error

```
$ make && ./bin/elixir test.exs
error: undefined function fake_fun/1 (expected Foo to define such a function or for it to be imported, but none are available)
  test.exs:12:23 Foo.bar/0
```

**Comment by viniciusmuller** [comment]
Related: https://github.com/elixir-lang/elixir/issues/12583

**Comment by josevalim** [comment]
Correct. We have started adding columns but we are doing so organically. :)

**Comment by viniciusmuller** [comment]
Hey @josevalim, could you provide me a starting point to work on this? Not sure if understand the  *organically* part exactly.

**Comment by josevalim** [comment]
@viniciusmuller I just pushed a commit for columns in unused variable warnings. We will now include the column when possible but sometimes we are simply not passing the column information when emitting the warning. For example, to detect unused variables, we need to track where they are defined, and we were storing only the line. Now we store the whole meta and it works.

So the work we need to do from now is to store the relevant column information. You can for example giving a try at adding column information to unused aliases and imports. :) Unknown function calls is also possible, but a bit harder.

PRs are very welcome! <3

**Comment by viniciusmuller** [comment]
I'll give it a try, thanks!

**Comment by viniciusmuller** [comment]
@josevalim  managed to open a PR for the unused aliases and imports (#12593), but I couln't find a nice way to test the unknown functions scenario yet:

This is what I'm trying:

```elixir
# Code.put_compiler_option(:parser_options, columns: true)
Code.compiler_options(parser_options: [columns: true])
IO.inspect(Code.compiler_options())

sample = """
a = 1
foo()
"""

ast = Code.string_to_quoted!(sample)
Code.with_diagnostics(fn -> 
  Code.eval_quoted(ast, [])
end)
```

```
$ elixir test.exs
%{
  debug_info: true,
  docs: true,
  ignore_already_consolidated: false,
  ignore_module_conflict: false,
  no_warn_undefined: [],
  parser_options: [columns: true],
  relative_paths: true,
  tracers: [],
  warnings_as_errors: false
}
[{line,2}]
** (CompileError) nofile: cannot compile file (errors have been logged)
    (elixir 1.15.0-rc.0) lib/code.ex:996: Code.eval_quoted/3
    (elixir 1.15.0-rc.0) lib/code.ex:572: Code.with_diagnostics/2
```

It seems that the compiler option is not having effect, although there are some tests that do this, am I missing something?

**Comment by viniciusmuller** [comment]
Another question that came to mind while working on it:

Is the correct behaviour for the `Code.with_diagnostics`, function to crash when there are compilation errors inside it?
```ex
sample = """
a = 1
foo()
"""

Code.with_diagnostics(fn -> 
  ast = Code.string_to_quoted!(sample)
  Code.eval_quoted(ast, [])
end)
```

```sh
elixir test.exs
** (CompileError) nofile: cannot compile file (errors have been logged)
    (elixir 1.15.0-rc.0) lib/code.ex:996: Code.eval_quoted/3
    (elixir 1.15.0-rc.0) lib/code.ex:572: Code.with_diagnostics/2

```
It seems to me that, it can also return errors from the type signature.

**Comment by viniciusmuller** [comment]
I've managed to get started [with this](https://github.com/viniciusmuller:elixir:add-column-unknown-function-call), but I'm a bit confused about how those errors are being generated here, do you have any pointers?

I guess I'm still missing a bit of  the "big-picture" about how the compilation and bootstrapping workflow is set, is there any documentation written on this? I couldn't find in the repo.

**Comment by josevalim** [comment]
We don't have internal documentation for this part of the code base, unfortunately. Also, keep in mind there is a difference for errors raised inside functions themselves or outside. Outside of a function, it happens here: https://github.com/elixir-lang/elixir/blob/main/lib/elixir/src/elixir_expand.erl#L843 And it should include the column. Inside functions, it is there: https://github.com/elixir-lang/elixir/blob/main/lib/elixir/src/elixir_locals.erl#L100
