### ISSUE TITLE
Downloadable epub of documentation broken

### ISSUE THREAD

**Issue by trypsynth** [elixir-lang/elixir#14753]
Hi,
The epub of the Elixir documentation I can download from https://hexdocs.pm/elixir/Elixir.epub doesn't load in any of the epub readers I have available.
Running epubcheck on it gives the following:
Messages: 10 fatals / 796 errors / 0 warnings / 0 infos
The errors are all over the place, from missing files to things like "FATAL(RSC-016): Elixir.epub/OEBPS/code-anti-patterns.xhtml(199,776): Fatal Error while parsing file: The entity name must immediately follow the '&'..."
is it possible for this to be looked into?
Thanks!

**Comment by josevalim** [comment]
Fixed in https://github.com/elixir-lang/ex_doc/commit/26a96dd3cb87c29f0ec50bc0861d0acb5a5e8a46

**Comment by trypsynth** [comment]
Thanks a ton! Is it possible for me to download (or build) the new epub?

**Comment by josevalim** [comment]
The one in main should be up to date:  https://hexdocs.pm/elixir/main/Elixir.epub

**Comment by trypsynth** [comment]
Hi,
Your fix reduced the error count by 1 from epubcheck, but I still get 10 critical and 795 errors.
The full log can be found [here](http://quinbox.xyz/a). It was nearly 80 kb, far too large for a GitHub comment.

**Comment by trypsynth** [comment]
Hi @josevalim just making sure this didn't fall under the radar, as seemingly I'm unable to reopen it.

**Comment by josevalim** [comment]
We track some of those in the ExDoc issues tracker, but they are not high priority unless they are fatal and block it from opening. I believe all fatal ones were addressed?

**Comment by trypsynth** [comment]
Not on my end at least. All that happened was your fix made epubcheck reduce the error count from 796 to 795. No epub reader I've found will open it.

**Comment by josevalim** [comment]
Hrm, it seems the build only picks up released ExDoc versions. So let me publish a new one and then it should be good once the next commit lands.

EDIT: We had already released this fix but for some reason it is still using v0.38.3, even though `curl -s https://hex.pm/api/packages/ex_doc | jq --raw-output '.latest_stable_version'` returns v0.38.4.

**Comment by josevalim** [comment]
For completeness, here is my local build:

```
$ epubcheck doc/elixir/Elixir.epub
ERROR(PKG-005): doc/elixir/Elixir.epub/./doc/elixir/Elixir.epub(-1,-1): The mimetype file has an extra field of length 28. The use of the extra field feature of the ZIP format is not permitted for the mimetype file.
Validating using EPUB version 3.3 rules.
ERROR(OPF-074): doc/elixir/Elixir.epub/OEBPS/content.opf(379,74): Package resource "OEBPS/assets/logo.png" is declared in several manifest item.
ERROR(OPF-014): doc/elixir/Elixir.epub/OEBPS/debugging.xhtml(-1,-1): The property "remote-resources" should be declared in the OPF file.
ERROR(RSC-001): doc/elixir/Elixir.epub/OEBPS/enum-cheat.xhtml(-1,-1): File "OEBPS/enum-cheat.xhtml" could not be found.
ERROR(CSS-008): doc/elixir/Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,7722): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(CSS-008): doc/elixir/Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,7862): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(CSS-008): doc/elixir/Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,8908): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(CSS-008): doc/elixir/Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,8908): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/basic-types.xhtml(56,274): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/basic-types.xhtml(88,391): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/basic-types.xhtml(104,300): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/basic-types.xhtml(104,369): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/basic-types.xhtml(104,437): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/basic-types.xhtml(104,507): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/pattern-matching.xhtml(15,303): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/pattern-matching.xhtml(52,187): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/case-cond-and-if.xhtml(23,233): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(35,1150): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(40,489): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(67,119): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(102,329): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/enumerable-and-streams.xhtml(26,124): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/structs.xhtml(38,240): Fragment identifier is not defined.
ERROR(RSC-006): doc/elixir/Elixir.epub/OEBPS/debugging.xhtml(49,720): Remote resource reference is not allowed in this context; resource "https://asciinema.org/a/509509.js" must be located in the EPUB container.
ERROR(RSC-006): doc/elixir/Elixir.epub/OEBPS/debugging.xhtml(49,1273): Remote resource reference is not allowed in this context; resource "https://asciinema.org/a/0h3po0AmTcBAorc5GBNU97nrs.js" must be located in the EPUB container.
ERROR(RSC-006): doc/elixir/Elixir.epub/OEBPS/debugging.xhtml(49,2140): Remote resource reference is not allowed in this context; resource "https://asciinema.org/a/XTZ15jFKFAlr8ZxIZMzaHgL5n.js" must be located in the EPUB container.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/code-anti-patterns.xhtml(199,867): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/code-anti-patterns.xhtml(203,447): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/design-anti-patterns.xhtml(155,489): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/task-and-gen-tcp.xhtml(54,780): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(15,4984): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(15,5753): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(15,5857): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(16,261): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(16,939): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(16,1963): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(16,2049): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(16,2139): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(16,2239): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(29,964): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(29,1046): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/operators.xhtml(29,1132): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(87,214): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(90,130): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(90,469): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(94,30): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(94,98): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(94,166): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(94,234): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(94,623): Fragment identifier is not defined.
ERROR(RSC-007): doc/elixir/Elixir.epub/OEBPS/patterns-and-guards.xhtml(94,2210): Referenced resource "OEBPS/Bitwise.html" could not be found in the EPUB.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/typespecs.xhtml(147,101): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(30,1486): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(75,63): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(75,120): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(75,178): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(76,19): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(210,60): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(220,61): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(250,60): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(260,61): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(814,63): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(1610,63): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(1620,63): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(1922,96): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(1947,174): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(1954,97): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(1979,176): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(2060,96): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(2085,174): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(2092,97): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(2117,176): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(3899,96): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(3917,293): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(3918,89): Fragment identifier is not defined.
ERROR(RSC-007): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(4556,54): Referenced resource "OEBPS/patterns-and-guards.html" could not be found in the EPUB.
ERROR(RSC-007): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(4558,53): Referenced resource "OEBPS/naming-conventions.html" could not be found in the EPUB.
ERROR(RSC-007): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(4615,54): Referenced resource "OEBPS/patterns-and-guards.html" could not be found in the EPUB.
ERROR(RSC-007): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(4618,53): Referenced resource "OEBPS/naming-conventions.html" could not be found in the EPUB.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(4973,65): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(6664,150): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(6665,121): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(6698,102): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(7075,96): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(7094,167): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(7095,427): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(7100,1416): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(7114,96): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.xhtml(7134,263): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(26,154): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(26,221): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(45,60): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(55,66): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(175,69): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(339,60): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(349,63): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(369,93): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(400,577): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(409,99): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(428,157): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(818,27): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(825,102): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(843,143): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(844,417): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(855,187): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(862,418): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(883,151): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(884,1345): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(893,508): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(902,172): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(914,221): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(1046,38): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2211,93): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2229,167): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2247,96): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2268,213): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(23,118): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(23,180): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(23,255): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(51,66): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(61,66): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(131,66): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(180,102): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(202,262): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(218,102): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(240,264): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(451,102): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Bitwise.xhtml(473,238): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Date.xhtml(33,229): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Date.xhtml(33,298): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/DateTime.xhtml(27,153): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/DateTime.xhtml(27,222): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/NaiveDateTime.xhtml(36,251): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/NaiveDateTime.xhtml(36,320): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/String.xhtml(24,184): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/String.xhtml(115,52): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Time.xhtml(33,229): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Time.xhtml(33,298): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(1718,149): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3856,31): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3856,110): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3859,544): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3859,614): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3859,684): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3859,754): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3864,31): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3926,58): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Enum.xhtml(3926,137): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Code.xhtml(1731,52): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Macro.xhtml(1400,42): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Macro.xhtml(2075,138): Fragment identifier is not defined.
ERROR(RSC-012): doc/elixir/Elixir.epub/OEBPS/Macro.xhtml(2079,138): Fragment identifier is not defined.

Check finished with errors
Messages: 0 fatals / 152 errors / 0 warnings / 0 infos
```

Thank you for following up!

**Comment by josevalim** [comment]
We should be good now!

**Comment by trypsynth** [comment]
Thanks! Where can I download it? https://hexdocs.pm/elixir/main/Elixir.epub still gives me the bad file.

**Comment by josevalim** [comment]
The file opens up fine and checks without critical/fatals here:

```
$ curl -o Elixir.epub https://hexdocs.pm/elixir/main/Elixir.epub && epubcheck Elixir.epub

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1842k  100 1842k    0     0  1122k      0  0:00:01  0:00:01 --:--:-- 1122k
ERROR(PKG-005): Elixir.epub/./Elixir.epub(-1,-1): The mimetype file has an extra field of length 28. The use of the extra field feature of the ZIP format is not permitted for the mimetype file.
Validating using EPUB version 3.3 rules.
ERROR(OPF-074): Elixir.epub/OEBPS/content.opf(375,74): Package resource "OEBPS/assets/logo.png" is declared in several manifest item.
ERROR(OPF-014): Elixir.epub/OEBPS/debugging.xhtml(-1,-1): The property "remote-resources" should be declared in the OPF file.
ERROR(RSC-001): Elixir.epub/OEBPS/enum-cheat.xhtml(-1,-1): File "OEBPS/enum-cheat.xhtml" could not be found.
ERROR(CSS-008): Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,7722): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(CSS-008): Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,7862): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(CSS-008): Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,8908): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(CSS-008): Elixir.epub/OEBPS/dist/epub-elixir-FNUUKFP7.css(1,8908): An error occurred while parsing the CSS: Token "code" not allowed here.
ERROR(RSC-012): Elixir.epub/OEBPS/basic-types.xhtml(56,274): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/basic-types.xhtml(88,391): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/basic-types.xhtml(104,300): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/basic-types.xhtml(104,369): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/basic-types.xhtml(104,437): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/basic-types.xhtml(104,507): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/pattern-matching.xhtml(15,303): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/pattern-matching.xhtml(60,187): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/case-cond-and-if.xhtml(23,233): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(35,1150): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(40,489): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(67,119): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/binaries-strings-and-charlists.xhtml(102,329): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/structs.xhtml(38,240): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/enumerable-and-streams.xhtml(26,124): Fragment identifier is not defined.
ERROR(RSC-006): Elixir.epub/OEBPS/debugging.xhtml(47,720): Remote resource reference is not allowed in this context; resource "https://asciinema.org/a/509509.js" must be located in the EPUB container.
ERROR(RSC-006): Elixir.epub/OEBPS/debugging.xhtml(47,1278): Remote resource reference is not allowed in this context; resource "https://asciinema.org/a/0h3po0AmTcBAorc5GBNU97nrs.js" must be located in the EPUB container.
ERROR(RSC-006): Elixir.epub/OEBPS/debugging.xhtml(47,2150): Remote resource reference is not allowed in this context; resource "https://asciinema.org/a/XTZ15jFKFAlr8ZxIZMzaHgL5n.js" must be located in the EPUB container.
ERROR(RSC-012): Elixir.epub/OEBPS/task-and-gen-tcp.xhtml(54,781): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/code-anti-patterns.xhtml(213,867): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/code-anti-patterns.xhtml(217,447): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/design-anti-patterns.xhtml(155,489): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(15,4984): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(15,5753): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(15,5857): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(16,261): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(16,939): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(16,1963): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(16,2049): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(16,2139): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(16,2239): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(29,964): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(29,1046): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/operators.xhtml(29,1132): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(94,214): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(97,130): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(97,469): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(101,30): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(101,98): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(101,166): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(101,234): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/patterns-and-guards.xhtml(101,755): Fragment identifier is not defined.
ERROR(RSC-007): Elixir.epub/OEBPS/patterns-and-guards.xhtml(101,2342): Referenced resource "OEBPS/Bitwise.html" could not be found in the EPUB.
ERROR(RSC-012): Elixir.epub/OEBPS/typespecs.xhtml(147,101): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(30,1486): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(75,63): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(75,120): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(75,178): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(76,19): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(210,60): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(220,61): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(250,60): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(260,61): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(836,63): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(1609,63): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(1619,63): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(1921,96): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(1946,174): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(1953,97): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(1978,176): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(2059,96): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(2084,174): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(2091,97): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(2116,176): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(4018,96): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(4036,293): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(4037,89): Fragment identifier is not defined.
ERROR(RSC-007): Elixir.epub/OEBPS/Kernel.xhtml(4675,54): Referenced resource "OEBPS/patterns-and-guards.html" could not be found in the EPUB.
ERROR(RSC-007): Elixir.epub/OEBPS/Kernel.xhtml(4677,53): Referenced resource "OEBPS/naming-conventions.html" could not be found in the EPUB.
ERROR(RSC-007): Elixir.epub/OEBPS/Kernel.xhtml(4734,54): Referenced resource "OEBPS/patterns-and-guards.html" could not be found in the EPUB.
ERROR(RSC-007): Elixir.epub/OEBPS/Kernel.xhtml(4737,53): Referenced resource "OEBPS/naming-conventions.html" could not be found in the EPUB.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(5112,65): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(6764,150): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(6765,121): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(6798,102): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(7175,96): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(7194,167): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(7195,427): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(7200,1416): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(7217,96): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.xhtml(7237,263): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(26,154): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(26,221): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(45,60): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(55,66): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(175,69): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(339,60): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(349,63): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(369,93): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(395,1092): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(404,99): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(423,157): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(813,27): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(820,102): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(838,143): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(839,417): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(850,187): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(857,418): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(878,151): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(879,1345): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(888,508): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(897,172): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(909,221): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(1040,38): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2212,93): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2230,167): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2249,96): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Kernel.SpecialForms.xhtml(2270,213): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(23,118): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(23,180): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(23,255): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(51,66): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(61,66): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(131,66): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(180,102): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(202,262): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(218,102): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(240,264): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(451,102): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Bitwise.xhtml(473,238): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Date.xhtml(33,229): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Date.xhtml(33,298): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/DateTime.xhtml(27,153): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/DateTime.xhtml(27,222): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/NaiveDateTime.xhtml(36,251): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/NaiveDateTime.xhtml(36,320): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/String.xhtml(24,184): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/String.xhtml(115,52): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Time.xhtml(33,229): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Time.xhtml(33,298): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(1725,149): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(2821,108): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(2877,127): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(2975,108): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3031,127): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3089,92): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3181,128): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3920,31): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3920,110): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3923,544): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3923,614): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3923,684): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3923,754): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3928,31): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3990,58): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Enum.xhtml(3990,137): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Process.xhtml(1427,130): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Code.xhtml(1916,52): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Macro.xhtml(1514,42): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Macro.xhtml(2197,138): Fragment identifier is not defined.
ERROR(RSC-012): Elixir.epub/OEBPS/Macro.xhtml(2201,138): Fragment identifier is not defined.

Check finished with errors
Messages: 0 fatals / 159 errors / 0 warnings / 0 infos

EPUBCheck completed
```

**Comment by trypsynth** [comment]
Hmm, yep it downloads now and doesn't give me any fatal errors, but I have 495 errors instead of your 159, and trying to load it into any sane epub reader still fails, like my project [paperback[(https://github.com/trypsynth/paperback) dies with this: Paperback  dialog  Unhandled standard exception of type "class parse_error" with message "File not found: OEBPS/enum-cheat.xhtml"; terminating the application.
When trying with a Python epub converter:
text.exceptions.ConversionError: "There is no item named 'OEBPS/enum-cheat.xhtml ' in the archive"

**Comment by josevalim** [comment]
The cheat sheet one should be straight-forward to include, although they won’t look good in epub.

**Comment by trypsynth** [comment]
I see this was closed, but I just wanted to extend a thanks to @josevalim for fixing this. Now I can read all the elixir documentation in my document reader of choice! Looking forward to using Elixir more :)
