### ISSUE TITLE
No longer able to format specific files with compile error present in different file

### ISSUE THREAD

**Issue by denvaar** [elixir-lang/elixir#14873]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.2.5.11] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.19.1 (compiled with Erlang/OTP 26)
```

### Operating system

MacOS Tahoe 26.0.1

### Current behavior

After upgrading to Elixir 1.18 -> 1.19.1, I noticed that I'm no longer able to `mix format <specific/file/a.ex>` if there is a compile error in  `<specific/file/b.ex>`. This seems to only be an issue under certain circumstances, which are:

- Only happens within an umbrella app.
- Only happens when at least one formatter plugin is present.

Here is a link to a project that can be used to illustrate the bug: https://github.com/denvaar/format_bug_umbrella/tree/main

To reproduce:

1. Modify `apps/app_a/lib/app_a.ex` to introduce a compile error such as:

```diff
--- a/apps/app_a/lib/app_a.ex
+++ b/apps/app_a/lib/app_a.ex
@@ -12,7 +12,7 @@ defmodule AppA do
       :world

   """
-  def hello do
+  def hello d
     :world
   end
 end
```

2. Attempt to format a different file from the top-level of the umbrella app: `MIX_DEBUG=1 mix format apps/app_a/lib/other.ex`

```
-> Running mix CLI
-> Running mix loadconfig (inside FormatBugUmbrella.MixProject)
<- Ran mix loadconfig in 2ms
-> Running mix format apps/app_a/lib/other.ex (inside FormatBugUmbrella.MixProject)
-> Running mix loadpaths (inside FormatBugUmbrella.MixProject)
-> Running mix deps.loadpaths (inside FormatBugUmbrella.MixProject)
-> Running mix archive.check (inside FormatBugUmbrella.MixProject)
<- Ran mix archive.check in 0ms
-> Running mix deps.precompile (inside FormatBugUmbrella.MixProject)
<- Ran mix deps.precompile in 0ms
==> app_a
-> Running mix compile --from-mix-deps-compile --no-warnings-as-errors --no-code-path-pruning (inside AppA.MixProject)
-> Running mix loadpaths --from-mix-deps-compile --no-warnings-as-errors --no-code-path-pruning (inside AppA.MixProject)
<- Ran mix loadpaths in 0ms
-> Running mix compile.all --from-mix-deps-compile --no-warnings-as-errors --no-code-path-pruning (inside AppA.MixProject)
-> Running mix compile.yecc --from-mix-deps-compile --no-warnings-as-errors --no-code-path-pruning (inside AppA.MixProject)
<- Ran mix compile.yecc in 2ms
-> Running mix compile.leex --from-mix-deps-compile --no-warnings-as-errors --no-code-path-pruning (inside AppA.MixProject)
<- Ran mix compile.leex in 0ms
-> Running mix compile.erlang --from-mix-deps-compile --no-warnings-as-errors --no-code-path-pruning (inside AppA.MixProject)
<- Ran mix compile.erlang in 0ms
-> Running mix compile.elixir --from-mix-deps-compile --no-warnings-as-errors --no-code-path-pruning (inside AppA.MixProject)
Compiling 1 file (.ex)

== Compilation error in file lib/app_a.ex ==
** (SyntaxError) invalid syntax found on lib/app_a.ex:18:1:
    error: unexpected reserved word: end
    hint: the "end" on line 17 may not have a matching "do" defined before it (based on indentation)
    │
 18 │ end
    │ ^
    │
    └─ lib/app_a.ex:18:1
    (elixir 1.19.1) lib/kernel/parallel_compiler.ex:483: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
<- Ran mix compile.elixir in 24ms
could not compile dependency :app_a, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile app_a --force", update it with "mix deps.update app_a" or clean it with "mix deps.clean app_a"
```

3. Repeat the above steps with either Elixir 1.18 or without the `plugins: [AppA.MyPlugin]` in the top-level `.formatter.exs` file, and see that it's not an issue.

### Expected behavior

Previously I was able to format a specific file successfully, regardless of whether or not some other file had an error.

**Comment by denvaar** [comment]
After looking closer, it seems like this was likely fixed in f175f5f3fa4eacffb8c0e53e563086890bb6b962 a few days ago. So, hopefully just need to wait for the new version bump.

**Comment by josevalim** [comment]
Thank you for the report! Did you try the v1.19 branch to confirm it or should I do it? :)

**Comment by denvaar** [comment]
> After looking closer, it seems like this was likely fixed in https://github.com/elixir-lang/elixir/commit/f175f5f3fa4eacffb8c0e53e563086890bb6b962 a few days ago. So, hopefully just need to wait for the new version bump.

Sorry - this is not true, I still get the error after force compile.

> Did you try the v1.19 branch

I just tried with a local installation (commit 7fa1914e88c6363a983b0d9e7e78c5925e02fce2) and it seems like it still happens. Sorry for the confusion, I had to `mix compile --force` prior to reproducing.

So, seems to happen with both latest and tag 1.19.1:

```
$ mix --version
Erlang/OTP 27 [erts-15.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Mix 1.20.0-dev (7fa1914) (compiled with Erlang/OTP 27)
```

```
$ mix --version
Erlang/OTP 27 [erts-15.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Mix 1.19.1 (compiled with Erlang/OTP 27)
```

**Comment by josevalim** [comment]
@denvaar I think you forgot to make the repository public :)

**Comment by josevalim** [comment]
However, I would expect for f175f5f3fa4eacffb8c0e53e563086890bb6b962 to fix it, since the root cause was us trying to compile umbrella dependencies, which no longer happens since that commit... what is the trace you see with `MIX_DEBUG=1`?

**Comment by denvaar** [comment]
Whoops - It's public now.

```
$ which mix
/Users/denvaar/code/elixir/bin/mix
$ which elixir
/Users/denvaar/code/elixir/bin/elixir
$ mix --version
Erlang/OTP 27 [erts-15.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Mix 1.20.0-dev (3a290c3) (compiled with Erlang/OTP 27)
```

```
$ MIX_DEBUG=1 mix compile --force
-> Running mix CLI
-> Running mix loadconfig (inside FormatBugUmbrella.MixProject)
<- Ran mix loadconfig in 3ms
-> Running mix compile --force (inside FormatBugUmbrella.MixProject)
-> Running mix loadpaths --force (inside FormatBugUmbrella.MixProject)
-> Running mix deps.loadpaths --force (inside FormatBugUmbrella.MixProject)
-> Running mix archive.check --force (inside FormatBugUmbrella.MixProject)
<- Ran mix archive.check in 0ms
<- Ran mix deps.loadpaths in 39ms
<- Ran mix loadpaths in 40ms
==> app_a
-> Running mix compile.all --force (inside AppA.MixProject)
-> Running mix compile.yecc --force (inside AppA.MixProject)
<- Ran mix compile.yecc in 1ms
-> Running mix compile.leex --force (inside AppA.MixProject)
<- Ran mix compile.leex in 0ms
-> Running mix compile.erlang --force (inside AppA.MixProject)
<- Ran mix compile.erlang in 0ms
-> Running mix compile.elixir --force (inside AppA.MixProject)
Compiling 3 files (.ex)
<- Ran mix compile.elixir in 33ms
-> Running mix compile.app --force (inside AppA.MixProject)
Generated app_a app
<- Ran mix compile.app in 6ms
<- Ran mix compile.all in 77ms
==> app_b
-> Running mix compile.all --force (inside AppB.MixProject)
-> Running mix compile.yecc --force (inside AppB.MixProject)
<- Ran mix compile.yecc in 0ms
-> Running mix compile.leex --force (inside AppB.MixProject)
<- Ran mix compile.leex in 0ms
-> Running mix compile.erlang --force (inside AppB.MixProject)
<- Ran mix compile.erlang in 0ms
-> Running mix compile.elixir --force (inside AppB.MixProject)
Compiling 1 file (.ex)
<- Ran mix compile.elixir in 27ms
-> Running mix compile.app --force (inside AppB.MixProject)
Generated app_b app
<- Ran mix compile.app in 0ms
<- Ran mix compile.all in 36ms
<- Ran mix compile in 315ms
<- Ran mix CLI in 368ms
```

Then I introduce the compile error in `app_a.ex`, as shown in my diff at the top:

```
$ vi apps/app_a/lib/app_a.ex
```

That gives me a compile error as expected:

```
$ MIX_DEBUG=1 mix compile --force
-> Running mix CLI
-> Running mix loadconfig (inside FormatBugUmbrella.MixProject)
<- Ran mix loadconfig in 2ms
-> Running mix compile --force (inside FormatBugUmbrella.MixProject)
-> Running mix loadpaths --force (inside FormatBugUmbrella.MixProject)
-> Running mix deps.loadpaths --force (inside FormatBugUmbrella.MixProject)
-> Running mix archive.check --force (inside FormatBugUmbrella.MixProject)
<- Ran mix archive.check in 0ms
<- Ran mix deps.loadpaths in 38ms
<- Ran mix loadpaths in 39ms
==> app_a
-> Running mix compile.all --force (inside AppA.MixProject)
-> Running mix compile.yecc --force (inside AppA.MixProject)
<- Ran mix compile.yecc in 1ms
-> Running mix compile.leex --force (inside AppA.MixProject)
<- Ran mix compile.leex in 0ms
-> Running mix compile.erlang --force (inside AppA.MixProject)
<- Ran mix compile.erlang in 0ms
-> Running mix compile.elixir --force (inside AppA.MixProject)
Compiling 3 files (.ex)

== Compilation error in file lib/app_a.ex ==
** (SyntaxError) invalid syntax found on lib/app_a.ex:18:1:
    error: unexpected reserved word: end
    hint: the "end" on line 17 may not have a matching "do" defined before it (based on indentation)
    │
 18 │ end
    │ ^
    │
    └─ lib/app_a.ex:18:1
    (elixir 1.20.0-dev) lib/kernel/parallel_compiler.ex:529: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
<- Ran mix compile.elixir in 27ms
```

Then I try to format `other.ex`, but it cannot:

```
$ MIX_DEGBUG=1 mix format apps/app_a/lib/other.ex
==> app_a
Compiling 3 files (.ex)

== Compilation error in file lib/app_a.ex ==
** (SyntaxError) invalid syntax found on lib/app_a.ex:18:1:
    error: unexpected reserved word: end
    hint: the "end" on line 17 may not have a matching "do" defined before it (based on indentation)
    │
 18 │ end
    │ ^
    │
    └─ lib/app_a.ex:18:1
    (elixir 1.20.0-dev) lib/kernel/parallel_compiler.ex:529: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

**Comment by josevalim** [comment]
Looking at the repro, I'd say this all expected. Here is what you are doing:

1. Introduce a compilation error
2. Run `mix compile --force` (the --force flag removes all previous build artifacts)
3. Run `mix format` (mix will notice that a plugin is missing and the `a` dependency was not compiled, so it attempts to compile it)

We could try to fix this issue, but it would mean attempting to format when we know a plugin or dependency is missing, which would lead to wrong formatting. Keep in mind that, if `mix compile` does not have the `--force` flag, then it all works since f175f5f3fa4eacffb8c0e53e563086890bb6b962 but not before. It is also worth noting that, the reproduction with the force flag also fails on v1.18.

So you were right, the issue was fixed, but your reproduction added an extra step that fails on both v1.18 and v1.19. :)
