### ISSUE TITLE
Mix tasks in local project should take precedence over mix archives

### ISSUE THREAD

**Issue by chrismccord** [elixir-lang/elixir#3376]
Example:

If you have the `phoenix.new` task installed as a mix archive, you cannnot run `mix phoenix.new` from the installer project and have the local project's task take precedent. The only solution is to remove the archive. The ideal fix seems to have the current mix project tasks take precedent over mix archive tasks.

**Comment by josevalim** [comment]
This is actually fixed in master. :D

**Comment by josevalim** [comment]
This is actually not fixed in master. :D

**Comment by Gazler** [comment]
Steps to reproduce: https://gist.github.com/Gazler/9d070fdbc72a8aef033b

**Comment by ericmj** [comment]
I don't think we should do this based on two things:

1. If the current project is compiled the task will be used from the project, but if not compiled it will be used from the archive. This behaviour would likely be weird and unexpected for users.

2. If a module the task calls is accidentally deleted/renamed the bug will be hidden until the archive is deleted because the module still exists in the archive.

**Comment by josevalim** [comment]
We can't fix this because it would mean we always need to compile the project to know if the task is there, as @ericmj said.
