### ISSUE TITLE
Failed to load crypto library on mac os

### ISSUE THREAD

**Issue by heiko-braun** [elixir-lang/elixir#5453]
### Environment

* Elixir version (elixir -v): Elixir 1.3.4
* Operating system: Mac OS

#### From ERL
Using the crypto library from erlang succeeds:

````
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.1  (abort with ^G)
1> crypto:strong_rand_bytes(16).
<<11,212,135,144,175,71,19,174,99,107,69,84,207,22,255,221>>


````

#### From Elixir (iex)

Using the same library from elixir fails:
````
08:41:36.251 [error] Unable to load crypto library. Failed with error:
":load, Library load-call unsuccessful."
OpenSSL might not be installed on this system.


08:41:36.251 [warn]  The on_load function for module crypto returned {:error, {:load, 'Library load-call unsuccessful.'}}

** (UndefinedFunctionError) function :crypto.supports/0 is undefined (module :crypto is not available)
     (crypto) :crypto.supports()
        (ssl) tls_v1.erl:262: :tls_v1.signature_algs/2
        (ssl) ssl.erl:1041: :ssl.handle_hashsigns_option/2
        (ssl) ssl.erl:728: :ssl.handle_options/2
        (ssl) ssl.erl:128: :ssl.connect/4
    (hackney) src/hackney_connect.erl:246: :hackney_connect.do_connect/5
    (hackney) src/hackney_connect.erl:37: :hackney_connect.connect/5
    (hackney) src/hackney.erl:328: :hackney.request/5

```

### Expected behavior

crypto should work form elixir as well.

**Comment by josevalim** [comment]
How are you starting Elixir and Erlang? Elixir does not do anything in particular to crypto, so it is unlikely to be an Elixir bug. :)

**Comment by heiko-braun** [comment]
Yes, it's strange. Using crypto straight from iex works as well:

```
iex(2)> :crypto.strong_rand_bytes(16)
<<106, 213, 80, 219, 233, 136, 129, 19, 254, 58, 199, 203, 28, 140, 34, 95>>
```

**Comment by heiko-braun** [comment]
I am running it through `iex -S mix`

**Comment by heiko-braun** [comment]
The function that yields the error works as well straight from iex:

```
iex(1)> :crypto.supports()
[hashs: [:sha, :sha224, :sha256, :sha384, :sha512, :md4, :md5, :ripemd160],
 ciphers: [:des3_cbc, :des_ede3, :des3_cbf, :des3_cfb, :aes_cbc, :aes_cbc128,
  :aes_cfb8, :aes_cfb128, :aes_cbc256, :aes_ctr, :aes_ecb, :aes_ige256,
  :des_cbc, :des_cfb, :des_ecb, :blowfish_cbc, :blowfish_cfb64, :blowfish_ofb64,
  :blowfish_ecb, :rc2_cbc, :rc4, :aes_gcm],
 public_keys: [:rsa, :dss, :dh, :ec_gf2m, :ecdsa, :ecdh, :srp]]

```

**Comment by josevalim** [comment]
Do you, by any chance, named your library :crypto or are depending on a project called :crypto?

**Comment by ericmj** [comment]
I have the same issue if I call `:observer.start` from iex and then call a function on `:crypto`:

```
iex(1)> :observer.start
:ok
iex(2)> :crypto.supports
09:28:21.558 [error] Unable to load crypto library. Failed with error:
":load, Library load-call unsuccessful."
OpenSSL might not be installed on this system.


09:28:21.567 [warn]  The on_load function for module crypto returned {:error, {:load, 'Library load-call unsuccessful.'}}
```

If I call `:crypto` first it works:

```
iex(1)> :crypto.supports
[hashs: [:sha, :sha224, :sha256, :sha384, :sha512, :md4, :md5, :ripemd160],
 ciphers: [:des3_cbc, :des_ede3, :des3_cbf, :des3_cfb, :aes_cbc, :aes_cbc128,
  :aes_cfb8, :aes_cfb128, :aes_cbc256, :aes_ctr, :aes_ecb, :aes_ige256,
  :des_cbc, :des_cfb, :des_ecb, :blowfish_cbc, :blowfish_cfb64, :blowfish_ofb64,
  :blowfish_ecb, :rc2_cbc, :rc4, :aes_gcm],
 public_keys: [:rsa, :dss, :dh, :ec_gf2m, :ecdsa, :ecdh, :srp]]
iex(2)> :observer.start
:ok
iex(3)> :crypto.supports
[hashs: [:sha, :sha224, :sha256, :sha384, :sha512, :md4, :md5, :ripemd160],
 ciphers: [:des3_cbc, :des_ede3, :des3_cbf, :des3_cfb, :aes_cbc, :aes_cbc128,
  :aes_cfb8, :aes_cfb128, :aes_cbc256, :aes_ctr, :aes_ecb, :aes_ige256,
  :des_cbc, :des_cfb, :des_ecb, :blowfish_cbc, :blowfish_cfb64, :blowfish_ofb64,
  :blowfish_ecb, :rc2_cbc, :rc4, :aes_gcm],
 public_keys: [:rsa, :dss, :dh, :ec_gf2m, :ecdsa, :ecdh, :srp]]
```

Looks like it has something to do with the order applications are loaded.

**Comment by ericmj** [comment]
This issue happens with `erl` as well so it's unlikely to be an Elixir issue.

**Comment by heiko-braun** [comment]
@josevalim no lib or dep called crypto

**Comment by heiko-braun** [comment]
@ericmj I agree, it's not really an elixir issue I think. @josevalim feel free to close this.

**Comment by heiko-braun** [comment]
For the record and to back up @ericmj observations:

Calling `:crypto.supports()` first works, but breaks if I first `:debugger.start` and then `:crypto.supports()`

This leads to the error mentioned before. I am pretty new to elixir/erlang, but maybe this does ring a bell for somebody else.

**Comment by josevalim** [comment]
What are your erlang versions?

**Comment by josevalim** [comment]
I meant to ask @ericmj, we already know @heiko-braun's. :) Also, how have you both installed it?

**Comment by heiko-braun** [comment]
I've recompiled erlang from source

**Comment by josevalim** [comment]
I can also reproduce it locally on both my Erlang installs. Closing this as an Erlang bug. I will see if someone has already reported it to the OTP team. Thank you!

**Comment by heiko-braun** [comment]
Thanks @josevalim

**Comment by PhillippOhlandt** [comment]
I just got the same issue with the observer and `:crypto`. Seems like it's not fixed yet.

**Comment by kenny-evitt** [comment]
I just observed this error today. I hadn't seen it before. I installed both Erlang and Elixir via `asdf`, long before today. My specific error:

```
$ mix dialyzer
Compiling 1 file (.ex)
Finding suitable PLTs
Checking PLT...
[:asn1, :certifi, :compiler, :connection, :crontab, :crypto, :db_connection, :decimal, :ecto, :ecto_sql, :elixir, :hackney, :idna, :jason, :kernel, :logger, :metrics, :mimerl, :pane, :postgrex, :public_key, :scribe, :ssl, :ssl_verify_fun, :stdlib, :telemetry, :tzdata, :unicode_util_compat]

10:45:53.045 [error] Unable to load crypto library. Failed with error:
":load_failed, Failed to load NIF library: 'dlopen(/Users/kenny/.asdf/installs/erlang/22.2.1/lib/crypto-4.6.3/priv/lib/crypto.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/kenny/.asdf/installs/erlang/22.2.1/lib/crypto-4.6.3/priv/lib/crypto.so
  Reason: image not found'"
OpenSSL might not be installed on this system.


10:45:53.050 [warn]  The on_load function for module crypto returned:
{:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/kenny/.asdf/installs/erlang/22.2.1/lib/crypto-4.6.3/priv/lib/crypto.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib\n  Referenced from: /Users/kenny/.asdf/installs/erlang/22.2.1/lib/crypto-4.6.3/priv/lib/crypto.so\n  Reason: image not found\''}}

** (UndefinedFunctionError) function :crypto.hash/2 is undefined (module :crypto is not available)
    (crypto) :crypto.hash(:sha, <<131, 116, 0, 0, 0, 22, 100, 0, 7, 99, 101, 114, 116, 105, 102, 105, 104, 7, 100, 0, 3, 104, 101, 120, 100, 0, 7, 99, 101, 114, 116, 105, 102, 105, 109, 0, 0, 0, 5, 50, 46, 53, 46, 49, 109, 0, 0, 0, 64, 56, ...>>)
    lib/mix/tasks/dialyzer.ex:384: Mix.Tasks.Dialyzer.dependency_hash/0
    lib/mix/tasks/dialyzer.ex:247: Mix.Tasks.Dialyzer.check_plt/1
    lib/mix/tasks/dialyzer.ex:172: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

What I *did* do recently – yesterday – was install the Homebrew `docutils` package. I had to 'overwrite links' for some Python files/libraries – apparently, because of the impending Python 2 EOL, Homebrew is working on removing Python 2 dependencies.

I wonder if OpenSSL – the version I have installed – depends on those Python 2 libraries.

**Comment by pdgonzalez872** [comment]
@kenny-evitt you may need to symlink `openssl`. Some folks had this issue and I looked into it a while back: https://github.com/kerl/kerl/issues/320#issuecomment-535632734. Hopefully this helps.

**Comment by kenny-evitt** [comment]
@pdgonzalez872 Thanks! Any ideas on how exactly I can symlink OpenSSL? Or why this is suddenly an issue?

This issue seems to be related tho it's more than five (5) years old!:

 - [Installing Elixir fails due to OpenSSL errors. · Issue #33218 · Homebrew/legacy-homebrew](https://github.com/Homebrew/legacy-homebrew/issues/33218)

**Comment by kenny-evitt** [comment]
`brew link ...` doesn't seem like it *can* help:

```
$ brew link openssl
Warning: Refusing to link macOS-provided software: openssl@1.1
If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
$ brew link -f openssl
Warning: Refusing to link macOS-provided software: openssl@1.1
If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by pdgonzalez872** [comment]
You may have different versions of `openssl` in your system and brew doesn't want to guess for you (that's my guess). This will show you if you have different versions:
```
$ ls /usr/local/opt/ | grep open
openssl
openssl@1.0
openssl@1.1
```

Questions:
- Have you tried setting the vars like the error message suggested?
- Maybe we move this to ElixirForum? This is not an Elixir issue. We can link the ElixirForum post here if necessary.

**Comment by kenny-evitt** [comment]
@pdgonzalez872 Elixir Forum post I just created for this:

 - [`Unable to load crypto library` error on macOS after running some Homebrew commands - Questions / Help - Elixir Forum](https://elixirforum.com/t/unable-to-load-crypto-library-error-on-macos-after-running-some-homebrew-commands/29105)

**Comment by paulstatezny** [comment]
Data point I hope will be helpful: This happened to me suddenly after installing Python3 via Homebrew. Uninstalling and rebuilding Erlang didn't work. 😭

**Comment by yaxhpal** [comment]
@paulstatezny I also faced the similar problem. For me this worked

`brew upgrade erlang`

Try this if you haven't got it resolved.

**Comment by catalx-team** [comment]
> @paulstatezny I also faced the similar problem. For me this worked
> 
> `brew upgrade erlang`
> 
> Try this if you haven't got it resolved.

fixed my issue!
the same thing happens as some others, suddenly happened after installing something via brew.

**Comment by ityonemo** [comment]
I've run into this error when running tests and (for me) it appears to be a race condition whereby the crypto app needs to be started before I can run tests (honestly that's never happened for me before), resolved by adding `Application.ensure_all_started(:crypto)` in `test_helpers.exs`

**Comment by makstackavenue9456** [comment]
> @paulstatezny I also faced the similar problem. For me this worked
> 
> `brew upgrade erlang`
> 
> Try this if you haven't got it resolved.

**Comment by jdmarshall** [comment]
I am still having this issue with erlang 25 and elixir 1.14.4 on OS X.

Using asdf.
