### ISSUE TITLE
Mix crashes when git returns error

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#6585]
### Environment

* Elixir & Erlang versions (elixir --version): erlang 20.0.5 elixir 1.5.1
* Operating system: macOS 10.12.6

### Current behavior

When running mix commands and git returns error mix crashes
```
$ mix deps.get
** (ArgumentError) argument error
    :erlang.iolist_to_binary([10, 10, 65, 103, 114, 101, 101, 105, 110, 103, 32, 116, 111, 32, 116, 104, 101, 32, 88, 99, 111, 100, 101, 47, 105, 79, 83, 32, 108, 105, 99, 101, 110, 115, 101, 32, 114, 101, 113, 117, 105, 114, 101, 115, 32, 97, 100, 109, 105, 110, ...])
    (mix) lib/mix/scm/git.ex:220: Mix.SCM.Git.get_rev_info/0
    (mix) lib/mix/scm/git.ex:61: anonymous fn/2 in Mix.SCM.Git.lock_status/1
    (elixir) lib/file.ex:1277: File.cd!/2
    (mix) lib/mix/dep.ex:284: Mix.Dep.check_lock/1
    (mix) lib/mix/dep/fetcher.ex:49: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:180: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:189: Mix.Dep.Converger.all/9
```

### Expected behavior
A proper error message like the one here:
```
$ brew update
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
```

**Comment by josevalim** [comment]
Good catch. We should probably print the message as is if we can't do the conversion to binary.

**Comment by lukaszsamson** [comment]
Not sure if the message was in std_out or std_error, from the docs looks like :os.cmd handles only std_out

**Comment by fishcakez** [comment]
Note that `:os.cmd` returns `charlist` and not `[byte], even though it doesn't help us actually resolve the handling of this, really we are doing the conversion wrong. So we should be able to convert but I guess if we did convert correctly in this case something strange would happen later..

**Comment by lukaszsamson** [comment]
Yes, there were probably some unicode chars returned, (see)[https://github.com/erlang/otp/blob/c84f6fa2dc7c7615e36a575571ee1a6e9cd586a4/lib/kernel/src/os.erl#L245]. However, shouldn't the process exit code be checked here in the first place?

**Comment by josevalim** [comment]
@fishcakez this particular piece of code was implemented as is for performance, since we need to do this lookup for every git dependency when we check dependencies. I checked the code and us being wrong is not a big issue because at worst it will say there is a lock mismatch. We will get an actual error later on, when we execute any of the git commands.

**Comment by josevalim** [comment]
Fixed in master and v1.5, thanks!

**Comment by fishcakez** [comment]
@josevalim if there is non-ASCII characters in the URL we would either get the wrong URL (if Latin1 range) or crash with argument (if UTF-8 range beyond latin1). We were crashing because of the UTF-8 range beyond 255.

However this doesn't resolve the issue, only handle the symptom (crash), we want to handle error cases, which I think means we need to use `System.cmd`? Using destructure here might be hiding these cases in a strange way.

**Comment by josevalim** [comment]
@fishcakez Yup, I agree about the URL, that's why 1c076f5de89bd31c97772439380354d59d80bac8 moved to List.to_string.

My point was just that we may still have false positives because of the use of destructure but that's fine because at best it will say the lock is wrong. If there is something misbehaving in their git, we will get the full error before we do any other git operation.

Does this clarify it?

**Comment by fishcakez** [comment]
I'm not sure there is a performance difference here between `System.cmd` and `:os.cmd`, aren't the implementations almost equivalent for this case and we are able to produce a nice error?

**Comment by josevalim** [comment]
@fishcakez Erlang was used to have a single port that the requests were sent through but that seems to no longer be the case. So you are right, we should just be using System.cmd. There is a small downside that we will need to do two queries instead of a single one but the cost is probably negligible then?

**Comment by fishcakez** [comment]
It shouldn't be but I guess we need to check :(.
