### ISSUE TITLE
mix can't compile syslog

### ISSUE THREAD

**Issue by rlipscombe** [elixir-lang/elixir#9998]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 10.13.3, OTP-22.3.3; _and_ Elixir 1.9.1, OTP-22.1.1
* Operating system: Ubuntu 18.04.4

### Description

I'm using `syslog` via the following:

    {:syslog, "~> 1.0.6", override: true},

Until yesterday, running `mix compile` resulted in `syslog_drv.so` being created. Starting yesterday, it stopped working.

What happened yesterday? I deleted my `~/.mix` directory (to investigate another problem). This resulted in me reinstalling rebar and rebar3.

The new version of rebar3 (rebar 3.13.1 on Erlang/OTP 22 Erts 10.7.1) doesn't generate the .so file. _But only when run from mix_, which is why I'm filing this here.

```
$ mix do deps.get, compile
* Getting syslog (Hex package)
===> Compiling syslog
===> Compiling lager_syslog
```

If I `cd deps/syslog && rebar3 compile`, it works:

```
deps/syslog $ ~/.mix/rebar3 compile
===> Fetching pc (from {git,"git://github.com/blt/port_compiler.git",{tag,"v1.6.0"}})
===> Compiling pc
===> Verifying dependencies...
===> Compiling syslog
===> Compiling c_src/syslog_drv.c
===> Linking priv/syslog_drv.so
```

Reverting to an earlier version of rebar3 (rebar 3.4.1 on Erlang/OTP 22 Erts 10.7.1) fixes it, as does using `manager: rebar` to force use of rebar2 (rebar 2.6.2 R15B03 20160628_123811 git 2.6.2).

Now, I'd file this as a rebar3 bug, except that it works when run directly, so I suspect something in the interaction between mix and rebar3...

**Comment by monkeygroover** [comment]
Also reported here https://github.com/Vagabond/erlang-syslog/issues/37

**Comment by ericmj** [comment]
Please show the full output when doing a fresh compile with `DEBUG=1` set.

**Comment by rlipscombe** [comment]
When it's not working:

```
$ rm -rf deps/syslog/
$ ~/.mix/rebar3 --version
rebar 3.13.1 on Erlang/OTP 22 Erts 10.5.1
$ DEBUG=1 mix do deps.get, compile
...
* Getting syslog (Hex package)
===> Expanded command sequence to be run: []
===> Provider: {default,do}
===> Expanded command sequence to be run: [{default,app_discovery},
                                           {bare,compile}]
===> Provider: {default,app_discovery}
===> Provider: {bare,compile}
===> Compiling syslog
===> run_hooks("/home/roger/Source/imp/imp_server/deps/syslog", pre_hooks, compile) -> no hooks defined

===> run_hooks("/home/roger/Source/imp/imp_server/deps/syslog", pre_hooks, erlc_compile) -> no hooks defined

===> erlopts [debug_info]
===> files to compile ["/home/roger/Source/imp/imp_server/deps/syslog/src/syslog_sup.erl",
                       "/home/roger/Source/imp/imp_server/deps/syslog/src/syslog.erl",
                       "/home/roger/Source/imp/imp_server/deps/syslog/src/syslog_app.erl"]
===> Starting 3 compile worker(s)
===>      Compiled /home/roger/Source/imp/imp_server/deps/syslog/src/syslog_sup.erl
===>      Compiled /home/roger/Source/imp/imp_server/deps/syslog/src/syslog_app.erl
===>      Compiled /home/roger/Source/imp/imp_server/deps/syslog/src/syslog.erl
===> run_hooks("/home/roger/Source/imp/imp_server/deps/syslog", post_hooks, erlc_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/imp/imp_server/deps/syslog", pre_hooks, app_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/imp/imp_server/deps/syslog", post_hooks, app_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/imp/imp_server/deps/syslog", post_hooks, compile) -> no hooks defined

===> Expanded command sequence to be run: []
===> Provider: {default,do}
===> Expanded command sequence to be run: [{default,app_discovery},
                                           {bare,compile}]
===> Provider: {default,app_discovery}
===> Provider: {bare,compile}
===> Compiling lager_syslog
```

**Comment by rlipscombe** [comment]
When it's working:

```
$ cp bin/rebar* ~/.mix
$ ~/.mix/rebar3 --version
rebar 3.4.1 on Erlang/OTP 22 Erts 10.5.1
$ rm -rf deps/syslog/
$ DEBUG=1 mix do deps.get, compile
...
* Getting syslog (Hex package)
===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                           {bare,compile}]
===> Evaluating config script "/home/roger/Source/foo/bar/deps/syslog/rebar.config.script"
===> Evaluating config script "/home/roger/Source/foo/bar/deps/syslog/rebar.config.script"
===> Fetching pc ({git,"git://github.com/blt/port_compiler.git",
                       {tag,"v1.6.0"}})
===> sh info:
	cwd: "/home/roger/Source/foo/bar/deps/syslog"
	cmd: git --version

===> 	opts: []

===> Port Cmd: git --version
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> sh info:
	cwd: "/home/roger/Source/foo/bar/deps/syslog"
	cmd: git clone git://github.com/blt/port_compiler.git .tmp_dir683875434364 -b v1.6.0 --single-branch

===> 	opts: [{cd,"/tmp"}]

===> Port Cmd: git clone git://github.com/blt/port_compiler.git .tmp_dir683875434364 -b v1.6.0 --single-branch
Port Opts: [{cd,"/tmp"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> sh info:
	cwd: "/home/roger/Source/foo/bar/deps/syslog"
	cmd: rm -rf /home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc

===> 	opts: [{use_stdout,false},abort_on_error]

===> Port Cmd: rm -rf /home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> Moving checkout "/tmp/.tmp_dir683875434364" to "/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc"
===> sh info:
	cwd: "/home/roger/Source/foo/bar/deps/syslog"
	cmd: mv /tmp/.tmp_dir683875434364 /home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc

===> 	opts: [{use_stdout,false},abort_on_error]

===> Port Cmd: mv /tmp/.tmp_dir683875434364 /home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> Compiling pc
===> run_hooks("/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc", pre_hooks, compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc", pre_hooks, erlc_compile) -> no hooks defined

===> erlopts [debug_info,debug_info,inline_list_funcs,
              warn_deprecated_function,warn_export_all,warn_export_vars,
              warn_obsolete_guard,warn_shadow_vars,warn_untyped_record,
              warn_unused_function,warn_unused_import,warnings_as_errors]
===> files to compile ["/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc/src/pc_port_env.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc/src/pc.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc/src/pc_prv_clean.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc/src/pc_compilation.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc/src/pc_util.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc/src/pc_prv_compile.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc/src/pc_port_specs.erl"]
===>      Compiled pc_port_env.erl
===>      Compiled pc.erl
===>      Compiled pc_prv_clean.erl
===>      Compiled pc_compilation.erl
===>      Compiled pc_util.erl
===>      Compiled pc_prv_compile.erl
===>      Compiled pc_port_specs.erl
===> run_hooks("/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc", post_hooks, erlc_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc", pre_hooks, app_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc", post_hooks, app_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog/_build/default/plugins/pc", post_hooks, compile) -> no hooks defined

===> Compiling syslog
===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", pre_hooks, compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", pre_hooks, erlc_compile) -> no hooks defined

===> erlopts [debug_info,debug_info,warnings_as_errors,warn_untyped_record,
              {d,namespaced_types}]
===> files to compile ["/home/roger/Source/foo/bar/deps/syslog/src/syslog_sup.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/src/syslog.erl",
                       "/home/roger/Source/foo/bar/deps/syslog/src/syslog_app.erl"]
===>      Compiled syslog_sup.erl
===>      Compiled syslog.erl
===>      Compiled syslog_app.erl
===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", post_hooks, erlc_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", pre_hooks, app_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", post_hooks, app_compile) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", pre_hooks, {pc,
                                                                            compile}) -> no hooks defined

===> sh info:
	cwd: "/home/roger/Source/foo/bar/deps/syslog"
	cmd: cc -c $CFLAGS -g -Wall -fPIC -MMD  -I"/home/roger/.kerl/erlangs/OTP-22.1.1/lib/erl_interface-3.13/include" -I"/home/roger/.kerl/erlangs/OTP-22.1.1/erts-10.5.1/include"   c_src/syslog_drv.c -o c_src/syslog_drv.o


...
lots of stuff ellided here, because it contains environment variables
...


===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", post_hooks, {pc,
                                                                             compile}) -> no hooks defined

===> run_hooks("/home/roger/Source/foo/bar/deps/syslog", post_hooks, compile) -> no hooks defined

===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                           {bare,compile}]
===> Compiling lager_syslog
```

**Comment by ericmj** [comment]
It looks like the bare compiler does not run the `provider_hooks` in 3.11.2.

/cc @tsloughter

**Comment by tsloughter** [comment]
Will take a look soon.

@rlipscombe would you be able to try downloading some other versions of rebar3 https://github.com/erlang/rebar3/releases and telling mix to use them and see if we can't narrow down the version that this started happening? Since there are at least 10 versions between 3.4 and 3.13.1.

**Comment by tsloughter** [comment]
3.6 is the only one that I can tell has a change that could possibly be related https://github.com/erlang/rebar3/commit/a74dc021cc9dd89b7448d894e262ebe5a82285cd#diff-e5ea4bb66076206fcc3edf5c135141a7

**Comment by tsloughter** [comment]
This person says it broke in 3.6.2 and claims this patch fixes it.. https://github.com/Vagabond/erlang-syslog/pull/36

**Comment by tsloughter** [comment]
@rlipscombe also, the output makes it look like `pc` isn't downloaded in the version that doesn't work. Is that just because it already existed (maybe that output was from running compile again with all the deps already fetched?) or is that actually what happens?

**Comment by rlipscombe** [comment]
Where does it download `pc` to? If it's in `deps/syslog`, then I deleted it between the two runs. So, yeah, if so, it didn't download it.

**Comment by tsloughter** [comment]
@rlipscombe ok, yea, based on the output it looks like it downloads them to `deps/syslog`. 

Can you try that persons fork/patch of erlang-syslog?

**Comment by rlipscombe** [comment]
> Can you try that persons fork/patch of erlang-syslog?

```
      {:syslog, git: "https://github.com/gatherdigital/erlang-syslog", ref: "645c16f6b2", override: true},
```

...does appear to fix it, yes.

**Comment by rlipscombe** [comment]
What I'm actually doing to fix it is putting rebar and rebar3 binaries in our repo (we already had these) and then using direnv to set `MIX_REBAR` and `MIX_REBAR3`, so we can make sure we're using consistent versions.

**Comment by tsloughter** [comment]
I'm reaching out to Andrew to get that PR merged. But no idea how it is fixing the issue, it doesn't look like it does anything.

**Comment by tsloughter** [comment]
My only guess is that the `erlang:function_exported(rebar3, main, 1)` stopped working for some reason. That would result in the configuration being rewritten to `[]` and that would explain why it doesn't even download the plugin in the broken version.

**Comment by josevalim** [comment]
Issue has been fixed upstream. Thanks everyone for the prompt replies!

**Comment by tsloughter** [comment]
New syslog has been published to hex https://hex.pm/packages/syslog/1.1.0

**Comment by ericmj** [comment]
Do we need a fix in rebar3 as well? The function exported check is unfortunately pretty uncommon.

@tsloughter Maybe the rebar3 module can be explicitly loaded to prevent this issue?

**Comment by tsloughter** [comment]
I'd say no since it is uncommon (or did you mean to say "common") and it is only for supporting rebar2 which has been deprecated for long enough.

But I also don't know how it is possible that exported check would fail while rebar3 is running.

**Comment by ericmj** [comment]
Yes, sorry I mean that it's common in projects that try to support both rebar2 and rebar3. Even though rebar2 is deprecated many projects still have this check.

**Comment by tsloughter** [comment]
Ah, ok, I didn't know of any.

But yea, still no idea how this could be happening and don't think we'll be able to investigate much. Maybe it is related to the improved code loading/unloading during compilation to not have conflicts but that shouldn't matter since rebar3 itself is not unloaded.
